// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using flatshare_server.Infrastructure.Repositories;

#nullable disable

namespace flatshare_server.Migrations
{
    [DbContext(typeof(FlatshareDbContext))]
    [Migration("20260321171212_Add UserSessions")]
    partial class AddUserSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Foo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Foos");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.User.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRole");

                    b.HasDiscriminator<string>("RoleType").HasValue("UserRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.User.LandlordRole", b =>
                {
                    b.HasBaseType("flatshare_server.Infrastructure.Model.User.UserRole");

                    b.HasDiscriminator().HasValue("LANDLORD");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.User.TenantRole", b =>
                {
                    b.HasBaseType("flatshare_server.Infrastructure.Model.User.UserRole");

                    b.HasDiscriminator().HasValue("TENANT");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.User.User", b =>
                {
                    b.OwnsOne("flatshare_server.Infrastructure.Model.AccountStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reason")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.User.UserRole", b =>
                {
                    b.HasOne("flatshare_server.Infrastructure.Model.User.User", "User")
                        .WithOne("Role")
                        .HasForeignKey("flatshare_server.Infrastructure.Model.User.UserRole", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.User.LandlordRole", b =>
                {
                    b.OwnsOne("flatshare_server.Infrastructure.Model.User.TenantCriteria", "TenantCriteria", b1 =>
                        {
                            b1.Property<int>("LandlordRoleId")
                                .HasColumnType("integer");

                            b1.HasKey("LandlordRoleId");

                            b1.ToTable("UserRole");

                            b1.WithOwner()
                                .HasForeignKey("LandlordRoleId");
                        });

                    b.Navigation("TenantCriteria")
                        .IsRequired();
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.User.TenantRole", b =>
                {
                    b.OwnsOne("flatshare_server.Infrastructure.Model.User.TenantPreferences", "TenantPreferences", b1 =>
                        {
                            b1.Property<int>("TenantRoleId")
                                .HasColumnType("integer");

                            b1.HasKey("TenantRoleId");

                            b1.ToTable("UserRole");

                            b1.WithOwner()
                                .HasForeignKey("TenantRoleId");
                        });

                    b.Navigation("TenantPreferences")
                        .IsRequired();
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.User.User", b =>
                {
                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
