// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using flatshare_server.Infrastructure.Repositories;

#nullable disable

namespace flatshare_server.Migrations
{
    [DbContext(typeof(FlatshareDbContext))]
    partial class FlatshareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Foo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Foos");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Listings.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AreaMeterSq")
                        .HasColumnType("real");

                    b.Property<DateOnly>("AvailableSince")
                        .HasColumnType("date");

                    b.Property<DateOnly>("AvailableUntil")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("Photos")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Listings_OwnerId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRole");

                    b.HasDiscriminator<string>("RoleType").HasValue("UserRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.LandlordRole", b =>
                {
                    b.HasBaseType("flatshare_server.Infrastructure.Model.Users.UserRole");

                    b.HasDiscriminator().HasValue("LANDLORD");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.TenantRole", b =>
                {
                    b.HasBaseType("flatshare_server.Infrastructure.Model.Users.UserRole");

                    b.HasDiscriminator().HasValue("TENANT");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Listings.Listing", b =>
                {
                    b.HasOne("flatshare_server.Infrastructure.Model.Users.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("flatshare_server.Infrastructure.Model.Listings.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AptNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ListingId");

                            b1.HasIndex("City", "District", "Street", "AptNumber")
                                .HasDatabaseName("IDX_Listing_Address");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("flatshare_server.Infrastructure.Model.Listings.ListingAttributes", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("CloseToShops")
                                .HasColumnType("boolean");

                            b1.Property<bool>("NonSmokingOnly")
                                .HasColumnType("boolean");

                            b1.Property<bool>("PetsAllowed")
                                .HasColumnType("boolean");

                            b1.Property<int>("Profile")
                                .HasColumnType("integer");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("flatshare_server.Infrastructure.Model.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Curr")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.User", b =>
                {
                    b.OwnsOne("flatshare_server.Infrastructure.Model.AccountStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reason")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.UserRole", b =>
                {
                    b.HasOne("flatshare_server.Infrastructure.Model.Users.User", "User")
                        .WithOne("Role")
                        .HasForeignKey("flatshare_server.Infrastructure.Model.Users.UserRole", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.LandlordRole", b =>
                {
                    b.OwnsOne("flatshare_server.Infrastructure.Model.Users.TenantCriteria", "TenantCriteria", b1 =>
                        {
                            b1.Property<int>("LandlordRoleId")
                                .HasColumnType("integer");

                            b1.HasKey("LandlordRoleId");

                            b1.ToTable("UserRole");

                            b1.WithOwner()
                                .HasForeignKey("LandlordRoleId");
                        });

                    b.Navigation("TenantCriteria")
                        .IsRequired();
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.TenantRole", b =>
                {
                    b.OwnsOne("flatshare_server.Infrastructure.Model.Users.TenantPreferences", "TenantPreferences", b1 =>
                        {
                            b1.Property<int>("TenantRoleId")
                                .HasColumnType("integer");

                            b1.Property<string>("Currency")
                                .HasColumnType("text");

                            b1.Property<decimal?>("MaxPrice")
                                .HasColumnType("numeric");

                            b1.Property<bool?>("PetsAllowed")
                                .HasColumnType("boolean");

                            b1.PrimitiveCollection<List<string>>("PreferredDistricts")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<bool?>("SmokingAllowed")
                                .HasColumnType("boolean");

                            b1.HasKey("TenantRoleId");

                            b1.ToTable("UserRole");

                            b1.WithOwner()
                                .HasForeignKey("TenantRoleId");
                        });

                    b.Navigation("TenantPreferences")
                        .IsRequired();
                });

            modelBuilder.Entity("flatshare_server.Infrastructure.Model.Users.User", b =>
                {
                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
