services:
  # Service 1: Main PostgreSQL Database
  bank-db:
    image: postgres:15-alpine
    container_name: flatshare-db-ct
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NieMaDowoduŻeWiedział
      POSTGRES_DB: flatshare_db
    ports:
      - "5432:5432"
    volumes:
      - flatshare_db:/var/lib/postgresql/data
    restart: always

volumes:
    flatshare_db: