name: Playwright Tests

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      DOCKER_COMPOSE_DIR: ./flatshare_server/flatshare_server
      DOTNET_SLN_DIR: ./flatshare_server
      FRONTEND_DIR: ./flatshare_frotend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Dependencies (Docker Compose)
        run: docker compose up db azurite -d
        working-directory: ${{ env.DOCKER_COMPOSE_DIR }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.DOTNET_SLN_DIR }}

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ${{ env.DOTNET_SLN_DIR }}

      - name: EF Installation
        run: dotnet tool install --global dotnet-ef
        working-directory: ${{ env.DOTNET_SLN_DIR }}

      - name: Drop Database
        run: dotnet ef database drop --force
        working-directory: ${{ env.DOCKER_COMPOSE_DIR }}

      - name: Update Database
        run: dotnet ef database update
        working-directory: ${{ env.DOCKER_COMPOSE_DIR }}

      - name: Start API
        run: dotnet run --configuration Release &
        working-directory: ${{ env.DOTNET_SLN_DIR }}/flatshare_server
        env:
          ASPNETCORE_URLS: https://localhost:7047

      - name: Run Playwright tests
        run: DEBUG=pw:webserver,pw:api npx playwright test --reporter=line
        working-directory: ${{ env.FRONTEND_DIR }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Stop Dependencies (Docker Compose)
        if: always()
        run: docker compose down -v
        working-directory: ${{ env.DOCKER_COMPOSE_DIR }}